LIBS-1228 - updated dependencies/image (compatibility to apple-chips)
springboot-testcontainer/springboot-testcontainer-mysql pull request #20
Opened 2023-03-28 12:47 UTC by Schubi1981

2023-03-29 15:51 UTC, julian-eggers approved these changes, later dismissed

2023-03-29 19:04 UTC, fegbers requested changes

2023-03-29 19:04 UTC, fegbers commented on pom.xml
>      </dependency>
Aus meiner Sicht ein Breaking-Change, einfach eine komplett andere Dependency zu verwenden, die zuvor überhaupt nicht verpflichtend war. Ich denke mal nicht, dass das automatisch funktionieren wird, wenn man noch den alten Connector verwendet?? Zudem ist die alte Maven-Property zur Überschreibung der Version entfallen, sodass die alte Überschreibung ggf. nicht mehr funktioniert.

2023-03-30 11:19 UTC, fegbers commented on pom.xml
>      </dependency>
https://avides.atlassian.net/browse/ITGS-107 um den Punkt ergänzt

2023-03-30 11:19 UTC, fegbers approved these changes

2023-03-30 11:22 UTC, julian-eggers approved these changes

2023-03-30 11:22 UTC, merged